server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizzardv2-db
    username: quizzardadmin
    password: quizzardpass123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
    locations: classpath:db/migration, classpath:db/repeatable
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}